version: '2'
services:
  bots3:
    image: splunk/splunk:8.0.3
    container_name: bots3
    volumes:
      - "splunk-var:/opt/splunk/var"
      - "splunk-etc:/opt/splunk/etc"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
      - SPLUNKBASE_USERNAME
      - SPLUNKBASE_PASSWORD
      - SPLUNK_APPS_URL
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8089:8089'

volumes:
  splunk-var:
  splunk-etc:
